number2String: number2String.c
	gcc -o number2String number2String.c

test: test.c
	gcc -o test test.c

hamilton: hamilton.o
	gcc -o hamilton hamilton.o

hamilton.o: hamilton.c
	gcc -c hamilton.c

hamiltonstepik: hamiltonstepik.o
	gcc -o hamiltonstepik hamiltonstepik.o

hamiltonstepik.o: hamiltonstepik.c
	gcc -c hamiltonstepik.c